create table category (
                            id bigint generated by default as identity,
                            description varchar(255) not null,
                            image_path varchar(255),
                            name varchar(100) not null,
                            primary key (id)
);

create table event (
                        id bigint generated by default as identity,
                        create_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP not null,
                        description varchar(100) not null,
                        image_path varchar(255),
                        location varchar(255) not null,
                        name varchar(255) not null,
                        participants integer not null,
                        target_date timestamp not null,
                        created_by bigint not null,
                        category_id bigint not null,
                        primary key (id)
);

create table user_event (
                             event_id bigint not null,
                             user_id bigint not null,
                             primary key (event_id, user_id)
);

create table app_user (
                       id bigint generated by default as identity,
                       create_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP not null,
                       email varchar(50) not null,
                       is_admin boolean default false,
                       nick varchar(20) not null,
                       password varchar(60) not null,
                       primary key (id)
);

alter table category
    add constraint category_name_uk unique (name);

alter table app_user
    add constraint app_user_email_uk unique (email);

alter table app_user
    add constraint app_user_nick_uk unique (nick);

alter table event
    add constraint event_category_fk
        foreign key (category_id)
    references category;

alter table event
    add constraint FKat8p3s7yjcp57lny4udqvqncq
        foreign key (user_id)
    references app_user;

alter table user_event
    add constraint user_event_user_fk
        foreign key (user_id)
    references app_user;

alter table user_event
    add constraint user_event_event_fk
        foreign key (event_id)
    references event;
